╒═══════════════════╤═══════════════╕
│ run config name   │               │
╞═══════════════════╪═══════════════╡
│ CONFIG_NAME       │ fusionda_cucd │
├───────────────────┼───────────────┤
│ device            │ cuda          │
├───────────────────┼───────────────┤
│ epochs            │ 20            │
├───────────────────┼───────────────┤
│ learning rate     │ 0.0001        │
├───────────────────┼───────────────┤
│ batch size        │ 4             │
╘═══════════════════╧═══════════════╛
down1: in 64, out 128
down2: in 128, out 128
up2: in 256, out 64
up1: in 128, out 64
down1: in 64, out 128
down2: in 128, out 128
up2: in 256, out 64
up1: in 128, out 64
Traceback (most recent call last):
  File "train_dualnetwork_cucd.py", line 208, in <module>
    run_training(cfg)
  File "train_dualnetwork_cucd.py", line 40, in run_training
    dataset = datasets.UrbanExtractionSpacenet7S1S2Dataset(cfg=cfg, dataset='training')
  File "C:\Users\shafner\repos\DDA_UrbanExtraction\utils\datasets.py", line 153, in __init__
    super().__init__(cfg)
  File "C:\Users\shafner\repos\DDA_UrbanExtraction\utils\datasets.py", line 24, in __init__
    self.s2_indices = self._get_indices(s2_bands, cfg.DATALOADER.SENTINEL2_BANDS)
  File "C:\Users\shafner\repos\DDA_UrbanExtraction\utils\datasets.py", line 55, in _get_indices
    return [bands.index(band) for band in selection]
  File "C:\Users\shafner\repos\DDA_UrbanExtraction\utils\datasets.py", line 55, in <listcomp>
    return [bands.index(band) for band in selection]
ValueError: 'B7' is not in list